import { HttpClientModule } from '@angular/common/http';
import { ComponentFixture, TestBed } from '@angular/core/testing';
import { FormsModule } from '@angular/forms';
import { MatButtonModule } from '@angular/material/button';
import { MatDialogModule } from '@angular/material/dialog';
import { MatDividerModule } from '@angular/material/divider';
import { MatExpansionModule } from '@angular/material/expansion';
import { MatFormFieldModule } from '@angular/material/form-field';
import { MatIconModule } from '@angular/material/icon';
import { MatInputModule } from '@angular/material/input';
import { MatMenuModule } from '@angular/material/menu';
import { MatPaginatorModule } from '@angular/material/paginator';
import { MatProgressBarModule } from '@angular/material/progress-bar';
import { MatProgressSpinnerModule } from '@angular/material/progress-spinner';
import { MatSelectModule } from '@angular/material/select';
import { BrowserModule } from '@angular/platform-browser';
import { BrowserAnimationsModule } from '@angular/platform-browser/animations';
import { NgParticlesModule } from 'ng-particles';
import { AppRoutingModule } from 'src/app/app-routing.module';
import { MatchListComponent } from '../match-list/match-list.component';

import { MatchDetailsComponent } from './match-details.component';
import { SquadComponent } from './squad/squad.component';

describe('MatchDetailsComponent', () => {
  let component: MatchDetailsComponent;
  let fixture: ComponentFixture<MatchDetailsComponent>;

  beforeEach(async () => {
    await TestBed.configureTestingModule({
      declarations: [ MatchDetailsComponent,
                      SquadComponent,
                      MatchListComponent ],
      imports: [ HttpClientModule,
        BrowserModule,
        AppRoutingModule,
        FormsModule,
        BrowserAnimationsModule,
        MatFormFieldModule,
        MatIconModule,
        MatInputModule,
        MatSelectModule,
        MatButtonModule,
        NgParticlesModule,
        HttpClientModule,
        MatProgressSpinnerModule,
        MatProgressBarModule,
        MatDividerModule,
        MatExpansionModule,
        MatPaginatorModule,
        MatDialogModule,
        MatMenuModule
]
    })
    .compileComponents();
  });

  beforeEach(() => {
    fixture = TestBed.createComponent(MatchDetailsComponent);
    component = fixture.componentInstance;
    component.match = {
      gameId: 5092875055,
      platformId: 'EUW1',
      gameCreation: 1613226648719,
      gameDuration: 2012,
      queueId: 420,
      mapId: 11,
      seasonId: 13,
      gameVersion: '11.3.357.5376',
      gameMode: 'CLASSIC',
      gameType: 'MATCHED_GAME',
      teams: [
          {
              teamId: 100,
              win: 'Fail',
              firstBlood: true,
              firstTower: true,
              firstInhibitor: true,
              firstBaron: false,
              firstDragon: false,
              firstRiftHerald: true,
              towerKills: 6,
              inhibitorKills: 1,
              baronKills: 0,
              dragonKills: 2,
              vilemawKills: 0,
              riftHeraldKills: 1,
              dominionVictoryScore: 0,
              bans: [
                  {
                      championId: 777,
                      pickTurn: 1
                  },
                  {
                      championId: 120,
                      pickTurn: 2
                  },
                  {
                      championId: 25,
                      pickTurn: 3
                  },
                  {
                      championId: 119,
                      pickTurn: 4
                  },
                  {
                      championId: 234,
                      pickTurn: 5
                  }
              ]
          },
          {
              teamId: 200,
              win: 'Win',
              firstBlood: false,
              firstTower: false,
              firstInhibitor: false,
              firstBaron: true,
              firstDragon: true,
              firstRiftHerald: false,
              towerKills: 8,
              inhibitorKills: 1,
              baronKills: 2,
              dragonKills: 3,
              vilemawKills: 0,
              riftHeraldKills: 0,
              dominionVictoryScore: 0,
              bans: [
                  {
                      championId: 157,
                      pickTurn: 6
                  },
                  {
                      championId: 58,
                      pickTurn: 7
                  },
                  {
                      championId: 99,
                      pickTurn: 8
                  },
                  {
                      championId: 360,
                      pickTurn: 9
                  },
                  {
                      championId: 11,
                      pickTurn: 10
                  }
              ]
          }
      ],
      participants: [
          {
              participantId: 1,
              teamId: 100,
              championId: 89,
              spell1Id: 14,
              spell2Id: 4,
              stats: {
                  participantId: 1,
                  win: false,
                  item0: 3047,
                  item1: 3190,
                  item2: 3860,
                  item3: 3107,
                  item4: 3076,
                  item5: 1028,
                  item6: 3364,
                  kills: 0,
                  deaths: 9,
                  assists: 20,
                  largestKillingSpree: 0,
                  largestMultiKill: 0,
                  killingSprees: 0,
                  longestTimeSpentLiving: 666,
                  doubleKills: 0,
                  tripleKills: 0,
                  quadraKills: 0,
                  pentaKills: 0,
                  unrealKills: 0,
                  totalDamageDealt: 38347,
                  magicDamageDealt: 21776,
                  physicalDamageDealt: 9114,
                  trueDamageDealt: 7456,
                  largestCriticalStrike: 14,
                  totalDamageDealtToChampions: 14357,
                  magicDamageDealtToChampions: 9755,
                  physicalDamageDealtToChampions: 3035,
                  trueDamageDealtToChampions: 1567,
                  totalHeal: 3611,
                  totalUnitsHealed: 3,
                  damageSelfMitigated: 42050,
                  damageDealtToObjectives: 1165,
                  damageDealtToTurrets: 1040,
                  visionScore: 73,
                  timeCCingOthers: 69,
                  totalDamageTaken: 29804,
                  magicalDamageTaken: 12430,
                  physicalDamageTaken: 16156,
                  trueDamageTaken: 1216,
                  goldEarned: 8490,
                  goldSpent: 7875,
                  turretKills: 0,
                  inhibitorKills: 0,
                  totalMinionsKilled: 37,
                  neutralMinionsKilled: 0,
                  neutralMinionsKilledTeamJungle: 0,
                  neutralMinionsKilledEnemyJungle: 0,
                  totalTimeCrowdControlDealt: 131,
                  champLevel: 13,
                  visionWardsBoughtInGame: 3,
                  sightWardsBoughtInGame: 0,
                  wardsPlaced: 26,
                  wardsKilled: 9,
                  firstBloodKill: false,
                  firstBloodAssist: false,
                  firstTowerKill: false,
                  firstTowerAssist: false,
                  firstInhibitorKill: false,
                  firstInhibitorAssist: false,
                  combatPlayerScore: 0,
                  objectivePlayerScore: 0,
                  totalPlayerScore: 0,
                  totalScoreRank: 0,
                  playerScore0: 0,
                  playerScore1: 0,
                  playerScore2: 0,
                  playerScore3: 0,
                  playerScore4: 0,
                  playerScore5: 0,
                  playerScore6: 0,
                  playerScore7: 0,
                  playerScore8: 0,
                  playerScore9: 0,
                  perk0: 8439,
                  perk0Var1: 1201,
                  perk0Var2: 0,
                  perk0Var3: 0,
                  perk1: 8446,
                  perk1Var1: 587,
                  perk1Var2: 0,
                  perk1Var3: 0,
                  perk2: 8444,
                  perk2Var1: 1417,
                  perk2Var2: 0,
                  perk2Var3: 0,
                  perk3: 8242,
                  perk3Var1: 85,
                  perk3Var2: 0,
                  perk3Var3: 0,
                  perk4: 8275,
                  perk4Var1: 11,
                  perk4Var2: 0,
                  perk4Var3: 0,
                  perk5: 8210,
                  perk5Var1: 5,
                  perk5Var2: 0,
                  perk5Var3: 0,
                  perkPrimaryStyle: 8400,
                  perkSubStyle: 8200,
                  statPerk0: 5008,
                  statPerk1: 5002,
                  statPerk2: 5001
              },
              timeline: {
                  participantId: 1,
                  creepsPerMinDeltas: {
                      '10-20': 1,
                      '0-10': 1.6,
                      '20-30': 1.1
                  },
                  xpPerMinDeltas: {
                      '10-20': 337.70000000000005,
                      '0-10': 247.7,
                      '20-30': 372.4
                  },
                  goldPerMinDeltas: {
                      '10-20': 289.3,
                      '0-10': 219.5,
                      '20-30': 228
                  },
                  csDiffPerMinDeltas: {
                      '10-20': 0.04999999999999982,
                      '0-10': 0.6499999999999997,
                      '20-30': 0.24999999999999933
                  },
                  xpDiffPerMinDeltas: {
                      '10-20': 43.25000000000006,
                      '0-10': 12.09999999999998,
                      '20-30': -12.149999999999977
                  },
                  damageTakenPerMinDeltas: {
                      '10-20': 647.5,
                      '0-10': 295.4,
                      '20-30': 1288.3
                  },
                  damageTakenDiffPerMinDeltas: {
                      '10-20': -39.19999999999999,
                      '0-10': 23.150000000000006,
                      '20-30': 225.8499999999999
                  },
                  role: 'DUO_SUPPORT',
                  lane: 'BOTTOM'
              }
          },
          {
              participantId: 2,
              teamId: 100,
              championId: 3,
              spell1Id: 4,
              spell2Id: 12,
              stats: {
                  participantId: 2,
                  win: false,
                  item0: 3152,
                  item1: 3193,
                  item2: 3157,
                  item3: 3020,
                  item4: 3076,
                  item5: 1011,
                  item6: 3340,
                  kills: 5,
                  deaths: 3,
                  assists: 10,
                  largestKillingSpree: 3,
                  largestMultiKill: 2,
                  killingSprees: 1,
                  longestTimeSpentLiving: 1069,
                  doubleKills: 1,
                  tripleKills: 0,
                  quadraKills: 0,
                  pentaKills: 0,
                  unrealKills: 0,
                  totalDamageDealt: 151443,
                  magicDamageDealt: 133583,
                  physicalDamageDealt: 8394,
                  trueDamageDealt: 9465,
                  largestCriticalStrike: 33,
                  totalDamageDealtToChampions: 26724,
                  magicDamageDealtToChampions: 26395,
                  physicalDamageDealtToChampions: 329,
                  trueDamageDealtToChampions: 0,
                  totalHeal: 3661,
                  totalUnitsHealed: 1,
                  damageSelfMitigated: 46523,
                  damageDealtToObjectives: 7595,
                  damageDealtToTurrets: 3558,
                  visionScore: 31,
                  timeCCingOthers: 39,
                  totalDamageTaken: 19754,
                  magicalDamageTaken: 4103,
                  physicalDamageTaken: 14998,
                  trueDamageTaken: 653,
                  goldEarned: 12785,
                  goldSpent: 12625,
                  turretKills: 0,
                  inhibitorKills: 0,
                  totalMinionsKilled: 195,
                  neutralMinionsKilled: 13,
                  neutralMinionsKilledTeamJungle: 8,
                  neutralMinionsKilledEnemyJungle: 1,
                  totalTimeCrowdControlDealt: 97,
                  champLevel: 17,
                  visionWardsBoughtInGame: 3,
                  sightWardsBoughtInGame: 0,
                  wardsPlaced: 12,
                  wardsKilled: 1,
                  firstBloodKill: false,
                  firstBloodAssist: false,
                  firstTowerKill: false,
                  firstTowerAssist: false,
                  firstInhibitorKill: false,
                  firstInhibitorAssist: false,
                  combatPlayerScore: 0,
                  objectivePlayerScore: 0,
                  totalPlayerScore: 0,
                  totalScoreRank: 0,
                  playerScore0: 0,
                  playerScore1: 0,
                  playerScore2: 0,
                  playerScore3: 0,
                  playerScore4: 0,
                  playerScore5: 0,
                  playerScore6: 0,
                  playerScore7: 0,
                  playerScore8: 0,
                  playerScore9: 0,
                  perk0: 8439,
                  perk0Var1: 1030,
                  perk0Var2: 0,
                  perk0Var3: 0,
                  perk1: 8401,
                  perk1Var1: 442,
                  perk1Var2: 0,
                  perk1Var3: 0,
                  perk2: 8473,
                  perk2Var1: 730,
                  perk2Var2: 0,
                  perk2Var3: 0,
                  perk3: 8451,
                  perk3Var1: 233,
                  perk3Var2: 0,
                  perk3Var3: 0,
                  perk4: 8143,
                  perk4Var1: 817,
                  perk4Var2: 0,
                  perk4Var3: 0,
                  perk5: 8134,
                  perk5Var1: 34,
                  perk5Var2: 5,
                  perk5Var3: 0,
                  perkPrimaryStyle: 8400,
                  perkSubStyle: 8100,
                  statPerk0: 5008,
                  statPerk1: 5003,
                  statPerk2: 5002
              },
              timeline: {
                  participantId: 2,
                  creepsPerMinDeltas: {
                      '10-20': 7,
                      '0-10': 6.9,
                      '20-30': 4.4
                  },
                  xpPerMinDeltas: {
                      '10-20': 504.70000000000005,
                      '0-10': 462.6,
                      '20-30': 521.5
                  },
                  goldPerMinDeltas: {
                      '10-20': 395,
                      '0-10': 291.2,
                      '20-30': 430.29999999999995
                  },
                  csDiffPerMinDeltas: {
                      '10-20': 2.1,
                      '0-10': 1.2999999999999998,
                      '20-30': 2.1
                  },
                  xpDiffPerMinDeltas: {
                      '10-20': -8.599999999999994,
                      '0-10': 28,
                      '20-30': 109.9
                  },
                  damageTakenPerMinDeltas: {
                      '10-20': 414.5,
                      '0-10': 189.39999999999998,
                      '20-30': 745.2
                  },
                  damageTakenDiffPerMinDeltas: {
                      '10-20': -461.2,
                      '0-10': -243.70000000000005,
                      '20-30': -1040.1
                  },
                  role: 'SOLO',
                  lane: 'MIDDLE'
              }
          },
          {
              participantId: 3,
              teamId: 100,
              championId: 107,
              spell1Id: 4,
              spell2Id: 11,
              stats: {
                  participantId: 3,
                  win: false,
                  item0: 3006,
                  item1: 6691,
                  item2: 6676,
                  item3: 6675,
                  item4: 1037,
                  item5: 1018,
                  item6: 3340,
                  kills: 8,
                  deaths: 12,
                  assists: 9,
                  largestKillingSpree: 3,
                  largestMultiKill: 1,
                  killingSprees: 1,
                  longestTimeSpentLiving: 448,
                  doubleKills: 0,
                  tripleKills: 0,
                  quadraKills: 0,
                  pentaKills: 0,
                  unrealKills: 0,
                  totalDamageDealt: 147692,
                  magicDamageDealt: 17115,
                  physicalDamageDealt: 119849,
                  trueDamageDealt: 10727,
                  largestCriticalStrike: 809,
                  totalDamageDealtToChampions: 20435,
                  magicDamageDealtToChampions: 1885,
                  physicalDamageDealtToChampions: 17481,
                  trueDamageDealtToChampions: 1069,
                  totalHeal: 15149,
                  totalUnitsHealed: 1,
                  damageSelfMitigated: 18219,
                  damageDealtToObjectives: 25275,
                  damageDealtToTurrets: 1661,
                  visionScore: 24,
                  timeCCingOthers: 10,
                  totalDamageTaken: 38226,
                  magicalDamageTaken: 13060,
                  physicalDamageTaken: 24678,
                  trueDamageTaken: 487,
                  goldEarned: 12985,
                  goldSpent: 12900,
                  turretKills: 2,
                  inhibitorKills: 0,
                  totalMinionsKilled: 19,
                  neutralMinionsKilled: 124,
                  neutralMinionsKilledTeamJungle: 75,
                  neutralMinionsKilledEnemyJungle: 21,
                  totalTimeCrowdControlDealt: 187,
                  champLevel: 15,
                  visionWardsBoughtInGame: 3,
                  sightWardsBoughtInGame: 0,
                  wardsPlaced: 7,
                  wardsKilled: 2,
                  firstBloodKill: false,
                  firstBloodAssist: false,
                  firstTowerKill: false,
                  firstTowerAssist: true,
                  firstInhibitorKill: false,
                  firstInhibitorAssist: false,
                  combatPlayerScore: 0,
                  objectivePlayerScore: 0,
                  totalPlayerScore: 0,
                  totalScoreRank: 0,
                  playerScore0: 0,
                  playerScore1: 0,
                  playerScore2: 0,
                  playerScore3: 1,
                  playerScore4: 0,
                  playerScore5: 0,
                  playerScore6: 0,
                  playerScore7: 0,
                  playerScore8: 0,
                  playerScore9: 0,
                  perk0: 8112,
                  perk0Var1: 1296,
                  perk0Var2: 0,
                  perk0Var3: 0,
                  perk1: 8143,
                  perk1Var1: 586,
                  perk1Var2: 0,
                  perk1Var3: 0,
                  perk2: 8138,
                  perk2Var1: 18,
                  perk2Var2: 0,
                  perk2Var3: 0,
                  perk3: 8105,
                  perk3Var1: 13,
                  perk3Var2: 5,
                  perk3Var3: 0,
                  perk4: 9111,
                  perk4Var1: 673,
                  perk4Var2: 340,
                  perk4Var3: 0,
                  perk5: 9104,
                  perk5Var1: 13,
                  perk5Var2: 0,
                  perk5Var3: 0,
                  perkPrimaryStyle: 8100,
                  perkSubStyle: 8000,
                  statPerk0: 5005,
                  statPerk1: 5008,
                  statPerk2: 5002
              },
              timeline: {
                  participantId: 3,
                  creepsPerMinDeltas: {
                      '10-20': 0.5,
                      '0-10': 0,
                      '20-30': 1.4000000000000001
                  },
                  xpPerMinDeltas: {
                      '10-20': 504.2,
                      '0-10': 291.20000000000005,
                      '20-30': 451.1
                  },
                  goldPerMinDeltas: {
                      '10-20': 473.5,
                      '0-10': 238.6,
                      '20-30': 453.6
                  },
                  csDiffPerMinDeltas: {
                      '10-20': 0.4,
                      '0-10': -0.30000000000000004,
                      '20-30': -2.5
                  },
                  xpDiffPerMinDeltas: {
                      '10-20': 77.19999999999999,
                      '0-10': 10.700000000000017,
                      '20-30': -279
                  },
                  damageTakenPerMinDeltas: {
                      '10-20': 1152.4,
                      '0-10': 717.5,
                      '20-30': 1243.4
                  },
                  damageTakenDiffPerMinDeltas: {
                      '10-20': 74.69999999999999,
                      '0-10': 119,
                      '20-30': -63.10000000000002
                  },
                  role: 'NONE',
                  lane: 'JUNGLE'
              }
          },
          {
              participantId: 4,
              teamId: 100,
              championId: 164,
              spell1Id: 12,
              spell2Id: 4,
              stats: {
                  participantId: 4,
                  win: false,
                  item0: 3074,
                  item1: 6632,
                  item2: 3047,
                  item3: 6333,
                  item4: 3123,
                  item5: 0,
                  item6: 3340,
                  kills: 8,
                  deaths: 8,
                  assists: 5,
                  largestKillingSpree: 5,
                  largestMultiKill: 1,
                  killingSprees: 2,
                  longestTimeSpentLiving: 915,
                  doubleKills: 0,
                  tripleKills: 0,
                  quadraKills: 0,
                  pentaKills: 0,
                  unrealKills: 0,
                  totalDamageDealt: 92481,
                  magicDamageDealt: 558,
                  physicalDamageDealt: 70028,
                  trueDamageDealt: 21894,
                  largestCriticalStrike: 0,
                  totalDamageDealtToChampions: 20775,
                  magicDamageDealtToChampions: 558,
                  physicalDamageDealtToChampions: 15629,
                  trueDamageDealtToChampions: 4587,
                  totalHeal: 8015,
                  totalUnitsHealed: 1,
                  damageSelfMitigated: 44012,
                  damageDealtToObjectives: 13476,
                  damageDealtToTurrets: 4947,
                  visionScore: 9,
                  timeCCingOthers: 27,
                  totalDamageTaken: 34485,
                  magicalDamageTaken: 10671,
                  physicalDamageTaken: 20291,
                  trueDamageTaken: 3522,
                  goldEarned: 12125,
                  goldSpent: 12250,
                  turretKills: 2,
                  inhibitorKills: 0,
                  totalMinionsKilled: 144,
                  neutralMinionsKilled: 0,
                  neutralMinionsKilledTeamJungle: 0,
                  neutralMinionsKilledEnemyJungle: 0,
                  totalTimeCrowdControlDealt: 189,
                  champLevel: 15,
                  visionWardsBoughtInGame: 0,
                  sightWardsBoughtInGame: 0,
                  wardsPlaced: 7,
                  wardsKilled: 0,
                  firstBloodKill: true,
                  firstBloodAssist: false,
                  firstTowerKill: true,
                  firstTowerAssist: false,
                  firstInhibitorKill: false,
                  firstInhibitorAssist: false,
                  combatPlayerScore: 0,
                  objectivePlayerScore: 0,
                  totalPlayerScore: 0,
                  totalScoreRank: 0,
                  playerScore0: 0,
                  playerScore1: 0,
                  playerScore2: 0,
                  playerScore3: 0,
                  playerScore4: 0,
                  playerScore5: 0,
                  playerScore6: 0,
                  playerScore7: 0,
                  playerScore8: 0,
                  playerScore9: 0,
                  perk0: 8010,
                  perk0Var1: 59,
                  perk0Var2: 0,
                  perk0Var3: 0,
                  perk1: 9111,
                  perk1Var1: 863,
                  perk1Var2: 260,
                  perk1Var3: 0,
                  perk2: 9105,
                  perk2Var1: 18,
                  perk2Var2: 50,
                  perk2Var3: 0,
                  perk3: 8299,
                  perk3Var1: 383,
                  perk3Var2: 0,
                  perk3Var3: 0,
                  perk4: 8446,
                  perk4Var1: 1442,
                  perk4Var2: 0,
                  perk4Var3: 0,
                  perk5: 8444,
                  perk5Var1: 1239,
                  perk5Var2: 0,
                  perk5Var3: 0,
                  perkPrimaryStyle: 8000,
                  perkSubStyle: 8400,
                  statPerk0: 5005,
                  statPerk1: 5008,
                  statPerk2: 5003
              },
              timeline: {
                  participantId: 4,
                  creepsPerMinDeltas: {
                      '10-20': 4.5,
                      '0-10': 7.3999999999999995,
                      '20-30': 2.5
                  },
                  xpPerMinDeltas: {
                      '10-20': 338.7,
                      '0-10': 512.2,
                      '20-30': 407.29999999999995
                  },
                  goldPerMinDeltas: {
                      '10-20': 400.5,
                      '0-10': 374.29999999999995,
                      '20-30': 339.4
                  },
                  csDiffPerMinDeltas: {
                      '10-20': -3.3,
                      '0-10': 2.3,
                      '20-30': 0.3999999999999998
                  },
                  xpDiffPerMinDeltas: {
                      '10-20': -166.60000000000002,
                      '0-10': 146.50000000000003,
                      '20-30': -22.600000000000023
                  },
                  damageTakenPerMinDeltas: {
                      '10-20': 915.6,
                      '0-10': 380.8,
                      '20-30': 1468.3000000000002
                  },
                  damageTakenDiffPerMinDeltas: {
                      '10-20': 28.80000000000001,
                      '0-10': -51.500000000000014,
                      '20-30': -190.89999999999998
                  },
                  role: 'SOLO',
                  lane: 'TOP'
              }
          },
          {
              participantId: 5,
              teamId: 100,
              championId: 22,
              spell1Id: 7,
              spell2Id: 4,
              stats: {
                  participantId: 5,
                  win: false,
                  item0: 1038,
                  item1: 6671,
                  item2: 3153,
                  item3: 3085,
                  item4: 3033,
                  item5: 3006,
                  item6: 3340,
                  kills: 19,
                  deaths: 7,
                  assists: 6,
                  largestKillingSpree: 5,
                  largestMultiKill: 2,
                  killingSprees: 5,
                  longestTimeSpentLiving: 632,
                  doubleKills: 4,
                  tripleKills: 0,
                  quadraKills: 0,
                  pentaKills: 0,
                  unrealKills: 0,
                  totalDamageDealt: 181049,
                  magicDamageDealt: 9523,
                  physicalDamageDealt: 162611,
                  trueDamageDealt: 8914,
                  largestCriticalStrike: 414,
                  totalDamageDealtToChampions: 34691,
                  magicDamageDealtToChampions: 6950,
                  physicalDamageDealtToChampions: 27363,
                  trueDamageDealtToChampions: 378,
                  totalHeal: 4886,
                  totalUnitsHealed: 4,
                  damageSelfMitigated: 11512,
                  damageDealtToObjectives: 13412,
                  damageDealtToTurrets: 7741,
                  visionScore: 15,
                  timeCCingOthers: 60,
                  totalDamageTaken: 22644,
                  magicalDamageTaken: 5890,
                  physicalDamageTaken: 16250,
                  trueDamageTaken: 504,
                  goldEarned: 17032,
                  goldSpent: 15250,
                  turretKills: 2,
                  inhibitorKills: 1,
                  totalMinionsKilled: 214,
                  neutralMinionsKilled: 6,
                  neutralMinionsKilledTeamJungle: 0,
                  neutralMinionsKilledEnemyJungle: 2,
                  totalTimeCrowdControlDealt: 791,
                  champLevel: 17,
                  visionWardsBoughtInGame: 0,
                  sightWardsBoughtInGame: 0,
                  wardsPlaced: 2,
                  wardsKilled: 4,
                  firstBloodKill: false,
                  firstBloodAssist: false,
                  firstTowerKill: false,
                  firstTowerAssist: false,
                  firstInhibitorKill: true,
                  firstInhibitorAssist: false,
                  combatPlayerScore: 0,
                  objectivePlayerScore: 0,
                  totalPlayerScore: 0,
                  totalScoreRank: 0,
                  playerScore0: 0,
                  playerScore1: 0,
                  playerScore2: 0,
                  playerScore3: 1,
                  playerScore4: 0,
                  playerScore5: 0,
                  playerScore6: 0,
                  playerScore7: 0,
                  playerScore8: 0,
                  playerScore9: 0,
                  perk0: 8008,
                  perk0Var1: 2,
                  perk0Var2: 50,
                  perk0Var3: 0,
                  perk1: 8009,
                  perk1Var1: 3044,
                  perk1Var2: 0,
                  perk1Var3: 0,
                  perk2: 9104,
                  perk2Var1: 13,
                  perk2Var2: 0,
                  perk2Var3: 0,
                  perk3: 8014,
                  perk3Var1: 1020,
                  perk3Var2: 0,
                  perk3Var3: 0,
                  perk4: 8345,
                  perk4Var1: 3,
                  perk4Var2: 0,
                  perk4Var3: 0,
                  perk5: 8410,
                  perk5Var1: 155,
                  perk5Var2: 0,
                  perk5Var3: 0,
                  perkPrimaryStyle: 8000,
                  perkSubStyle: 8300,
                  statPerk0: 5005,
                  statPerk1: 5008,
                  statPerk2: 5002
              },
              timeline: {
                  participantId: 5,
                  creepsPerMinDeltas: {
                      '10-20': 6.699999999999999,
                      '0-10': 5.3,
                      '20-30': 8
                  },
                  xpPerMinDeltas: {
                      '10-20': 560,
                      '0-10': 310.7,
                      '20-30': 693.8
                  },
                  goldPerMinDeltas: {
                      '10-20': 574.2,
                      '0-10': 338.29999999999995,
                      '20-30': 519.7
                  },
                  csDiffPerMinDeltas: {
                      '10-20': 0.04999999999999982,
                      '0-10': 0.6499999999999997,
                      '20-30': 0.24999999999999933
                  },
                  xpDiffPerMinDeltas: {
                      '10-20': 43.25000000000006,
                      '0-10': 12.09999999999998,
                      '20-30': -12.149999999999977
                  },
                  damageTakenPerMinDeltas: {
                      '10-20': 565.4,
                      '0-10': 394.6,
                      '20-30': 706.2
                  },
                  damageTakenDiffPerMinDeltas: {
                      '10-20': -39.19999999999999,
                      '0-10': 23.150000000000006,
                      '20-30': 225.8499999999999
                  },
                  role: 'DUO_CARRY',
                  lane: 'BOTTOM'
              }
          },
          {
              participantId: 6,
              teamId: 200,
              championId: 59,
              spell1Id: 11,
              spell2Id: 4,
              stats: {
                  participantId: 6,
                  win: true,
                  item0: 6630,
                  item1: 3071,
                  item2: 3047,
                  item3: 3075,
                  item4: 3211,
                  item5: 3044,
                  item6: 3364,
                  kills: 7,
                  deaths: 7,
                  assists: 18,
                  largestKillingSpree: 3,
                  largestMultiKill: 1,
                  killingSprees: 2,
                  longestTimeSpentLiving: 420,
                  doubleKills: 0,
                  tripleKills: 0,
                  quadraKills: 0,
                  pentaKills: 0,
                  unrealKills: 0,
                  totalDamageDealt: 152943,
                  magicDamageDealt: 21470,
                  physicalDamageDealt: 119509,
                  trueDamageDealt: 11962,
                  largestCriticalStrike: 16,
                  totalDamageDealtToChampions: 19384,
                  magicDamageDealtToChampions: 2705,
                  physicalDamageDealtToChampions: 15325,
                  trueDamageDealtToChampions: 1354,
                  totalHeal: 13807,
                  totalUnitsHealed: 1,
                  damageSelfMitigated: 38150,
                  damageDealtToObjectives: 21566,
                  damageDealtToTurrets: 3001,
                  visionScore: 15,
                  timeCCingOthers: 30,
                  totalDamageTaken: 38219,
                  magicalDamageTaken: 13089,
                  physicalDamageTaken: 23011,
                  trueDamageTaken: 2118,
                  goldEarned: 14765,
                  goldSpent: 13550,
                  turretKills: 1,
                  inhibitorKills: 1,
                  totalMinionsKilled: 49,
                  neutralMinionsKilled: 127,
                  neutralMinionsKilledTeamJungle: 74,
                  neutralMinionsKilledEnemyJungle: 13,
                  totalTimeCrowdControlDealt: 423,
                  champLevel: 17,
                  visionWardsBoughtInGame: 0,
                  sightWardsBoughtInGame: 0,
                  wardsPlaced: 2,
                  wardsKilled: 2,
                  firstBloodKill: false,
                  firstBloodAssist: false,
                  firstTowerKill: false,
                  firstTowerAssist: false,
                  firstInhibitorKill: false,
                  firstInhibitorAssist: false,
                  combatPlayerScore: 0,
                  objectivePlayerScore: 0,
                  totalPlayerScore: 0,
                  totalScoreRank: 0,
                  playerScore0: 0,
                  playerScore1: 0,
                  playerScore2: 0,
                  playerScore3: 0,
                  playerScore4: 0,
                  playerScore5: 0,
                  playerScore6: 0,
                  playerScore7: 0,
                  playerScore8: 0,
                  playerScore9: 0,
                  perk0: 8010,
                  perk0Var1: 362,
                  perk0Var2: 0,
                  perk0Var3: 0,
                  perk1: 9111,
                  perk1Var1: 2282,
                  perk1Var2: 500,
                  perk1Var3: 0,
                  perk2: 9104,
                  perk2Var1: 16,
                  perk2Var2: 30,
                  perk2Var3: 0,
                  perk3: 8014,
                  perk3Var1: 552,
                  perk3Var2: 0,
                  perk3Var3: 0,
                  perk4: 8143,
                  perk4Var1: 405,
                  perk4Var2: 0,
                  perk4Var3: 0,
                  perk5: 8135,
                  perk5Var1: 4465,
                  perk5Var2: 5,
                  perk5Var3: 0,
                  perkPrimaryStyle: 8000,
                  perkSubStyle: 8100,
                  statPerk0: 5005,
                  statPerk1: 5008,
                  statPerk2: 5002
              },
              timeline: {
                  participantId: 6,
                  creepsPerMinDeltas: {
                      '10-20': 0.1,
                      '0-10': 0.30000000000000004,
                      '20-30': 3.9000000000000004
                  },
                  xpPerMinDeltas: {
                      '10-20': 427,
                      '0-10': 280.5,
                      '20-30': 730.0999999999999
                  },
                  goldPerMinDeltas: {
                      '10-20': 482.29999999999995,
                      '0-10': 251.7,
                      '20-30': 475.29999999999995
                  },
                  csDiffPerMinDeltas: {
                      '10-20': -0.4,
                      '0-10': 0.30000000000000004,
                      '20-30': 2.5
                  },
                  xpDiffPerMinDeltas: {
                      '10-20': -77.19999999999999,
                      '0-10': -10.700000000000017,
                      '20-30': 279
                  },
                  damageTakenPerMinDeltas: {
                      '10-20': 1077.7,
                      '0-10': 598.5,
                      '20-30': 1306.5
                  },
                  damageTakenDiffPerMinDeltas: {
                      '10-20': -74.69999999999999,
                      '0-10': -119,
                      '20-30': 63.10000000000002
                  },
                  role: 'NONE',
                  lane: 'JUNGLE'
              }
          },
          {
              participantId: 7,
              teamId: 200,
              championId: 222,
              spell1Id: 4,
              spell2Id: 7,
              stats: {
                  participantId: 7,
                  win: true,
                  item0: 3094,
                  item1: 6671,
                  item2: 3006,
                  item3: 3085,
                  item4: 3033,
                  item5: 1053,
                  item6: 3340,
                  kills: 11,
                  deaths: 8,
                  assists: 10,
                  largestKillingSpree: 4,
                  largestMultiKill: 2,
                  killingSprees: 3,
                  longestTimeSpentLiving: 533,
                  doubleKills: 3,
                  tripleKills: 0,
                  quadraKills: 0,
                  pentaKills: 0,
                  unrealKills: 0,
                  totalDamageDealt: 195028,
                  magicDamageDealt: 4429,
                  physicalDamageDealt: 173756,
                  trueDamageDealt: 16841,
                  largestCriticalStrike: 433,
                  totalDamageDealtToChampions: 23956,
                  magicDamageDealtToChampions: 1757,
                  physicalDamageDealtToChampions: 21707,
                  trueDamageDealtToChampions: 491,
                  totalHeal: 3464,
                  totalUnitsHealed: 4,
                  damageSelfMitigated: 10584,
                  damageDealtToObjectives: 13888,
                  damageDealtToTurrets: 9585,
                  visionScore: 20,
                  timeCCingOthers: 22,
                  totalDamageTaken: 21563,
                  magicalDamageTaken: 5271,
                  physicalDamageTaken: 15397,
                  trueDamageTaken: 895,
                  goldEarned: 15817,
                  goldSpent: 13800,
                  turretKills: 5,
                  inhibitorKills: 0,
                  totalMinionsKilled: 213,
                  neutralMinionsKilled: 12,
                  neutralMinionsKilledTeamJungle: 8,
                  neutralMinionsKilledEnemyJungle: 0,
                  totalTimeCrowdControlDealt: 133,
                  champLevel: 16,
                  visionWardsBoughtInGame: 2,
                  sightWardsBoughtInGame: 0,
                  wardsPlaced: 13,
                  wardsKilled: 1,
                  firstBloodKill: false,
                  firstBloodAssist: false,
                  firstTowerKill: false,
                  firstTowerAssist: false,
                  firstInhibitorKill: false,
                  firstInhibitorAssist: false,
                  combatPlayerScore: 0,
                  objectivePlayerScore: 0,
                  totalPlayerScore: 0,
                  totalScoreRank: 0,
                  playerScore0: 0,
                  playerScore1: 0,
                  playerScore2: 0,
                  playerScore3: 0,
                  playerScore4: 0,
                  playerScore5: 0,
                  playerScore6: 0,
                  playerScore7: 0,
                  playerScore8: 0,
                  playerScore9: 0,
                  perk0: 8008,
                  perk0Var1: 2,
                  perk0Var2: 30,
                  perk0Var3: 0,
                  perk1: 8009,
                  perk1Var1: 2864,
                  perk1Var2: 0,
                  perk1Var3: 0,
                  perk2: 9104,
                  perk2Var1: 16,
                  perk2Var2: 10,
                  perk2Var3: 0,
                  perk3: 8014,
                  perk3Var1: 651,
                  perk3Var2: 0,
                  perk3Var3: 0,
                  perk4: 8275,
                  perk4Var1: 11,
                  perk4Var2: 0,
                  perk4Var3: 0,
                  perk5: 8236,
                  perk5Var1: 28,
                  perk5Var2: 0,
                  perk5Var3: 0,
                  perkPrimaryStyle: 8000,
                  perkSubStyle: 8200,
                  statPerk0: 5005,
                  statPerk1: 5008,
                  statPerk2: 5002
              },
              timeline: {
                  participantId: 7,
                  creepsPerMinDeltas: {
                      '10-20': 6.6,
                      '0-10': 5.4,
                      '20-30': 8
                  },
                  xpPerMinDeltas: {
                      '10-20': 485.29999999999995,
                      '0-10': 259,
                      '20-30': 580.5
                  },
                  goldPerMinDeltas: {
                      '10-20': 493.2,
                      '0-10': 205.10000000000002,
                      '20-30': 545.8
                  },
                  csDiffPerMinDeltas: {
                      '10-20': -0.04999999999999982,
                      '0-10': -0.6499999999999997,
                      '20-30': -0.24999999999999933
                  },
                  xpDiffPerMinDeltas: {
                      '10-20': -43.25000000000006,
                      '0-10': -12.09999999999998,
                      '20-30': 12.149999999999977
                  },
                  damageTakenPerMinDeltas: {
                      '10-20': 679.7,
                      '0-10': 315,
                      '20-30': 794.9000000000001
                  },
                  damageTakenDiffPerMinDeltas: {
                      '10-20': 39.19999999999999,
                      '0-10': -23.150000000000006,
                      '20-30': -225.8499999999999
                  },
                  role: 'DUO_CARRY',
                  lane: 'BOTTOM'
              }
          },
          {
              participantId: 8,
              teamId: 200,
              championId: 517,
              spell1Id: 4,
              spell2Id: 12,
              stats: {
                  participantId: 8,
                  win: true,
                  item0: 6655,
                  item1: 3157,
                  item2: 3020,
                  item3: 3100,
                  item4: 1058,
                  item5: 1058,
                  item6: 3340,
                  kills: 10,
                  deaths: 7,
                  assists: 12,
                  largestKillingSpree: 5,
                  largestMultiKill: 2,
                  killingSprees: 3,
                  longestTimeSpentLiving: 833,
                  doubleKills: 1,
                  tripleKills: 0,
                  quadraKills: 0,
                  pentaKills: 0,
                  unrealKills: 0,
                  totalDamageDealt: 140627,
                  magicDamageDealt: 127328,
                  physicalDamageDealt: 9702,
                  trueDamageDealt: 3596,
                  largestCriticalStrike: 0,
                  totalDamageDealtToChampions: 26682,
                  magicDamageDealtToChampions: 26150,
                  physicalDamageDealtToChampions: 261,
                  trueDamageDealtToChampions: 270,
                  totalHeal: 12791,
                  totalUnitsHealed: 1,
                  damageSelfMitigated: 23246,
                  damageDealtToObjectives: 16776,
                  damageDealtToTurrets: 3585,
                  visionScore: 17,
                  timeCCingOthers: 23,
                  totalDamageTaken: 39323,
                  magicalDamageTaken: 12495,
                  physicalDamageTaken: 25118,
                  trueDamageTaken: 1709,
                  goldEarned: 13669,
                  goldSpent: 13725,
                  turretKills: 1,
                  inhibitorKills: 0,
                  totalMinionsKilled: 140,
                  neutralMinionsKilled: 20,
                  neutralMinionsKilledTeamJungle: 11,
                  neutralMinionsKilledEnemyJungle: 4,
                  totalTimeCrowdControlDealt: 342,
                  champLevel: 17,
                  visionWardsBoughtInGame: 1,
                  sightWardsBoughtInGame: 0,
                  wardsPlaced: 10,
                  wardsKilled: 1,
                  firstBloodKill: false,
                  firstBloodAssist: false,
                  firstTowerKill: false,
                  firstTowerAssist: false,
                  firstInhibitorKill: false,
                  firstInhibitorAssist: false,
                  combatPlayerScore: 0,
                  objectivePlayerScore: 0,
                  totalPlayerScore: 0,
                  totalScoreRank: 0,
                  playerScore0: 0,
                  playerScore1: 0,
                  playerScore2: 0,
                  playerScore3: 0,
                  playerScore4: 0,
                  playerScore5: 0,
                  playerScore6: 0,
                  playerScore7: 0,
                  playerScore8: 0,
                  playerScore9: 0,
                  perk0: 8112,
                  perk0Var1: 1831,
                  perk0Var2: 0,
                  perk0Var3: 0,
                  perk1: 8143,
                  perk1Var1: 1178,
                  perk1Var2: 0,
                  perk1Var3: 0,
                  perk2: 8138,
                  perk2Var1: 30,
                  perk2Var2: 0,
                  perk2Var3: 0,
                  perk3: 8135,
                  perk3Var1: 4878,
                  perk3Var2: 5,
                  perk3Var3: 0,
                  perk4: 8210,
                  perk4Var1: 32,
                  perk4Var2: 0,
                  perk4Var3: 0,
                  perk5: 8236,
                  perk5Var1: 48,
                  perk5Var2: 0,
                  perk5Var3: 0,
                  perkPrimaryStyle: 8100,
                  perkSubStyle: 8200,
                  statPerk0: 5008,
                  statPerk1: 5008,
                  statPerk2: 5003
              },
              timeline: {
                  participantId: 8,
                  creepsPerMinDeltas: {
                      '10-20': 4.9,
                      '0-10': 5.6,
                      '20-30': 2.3
                  },
                  xpPerMinDeltas: {
                      '10-20': 513.3,
                      '0-10': 434.6,
                      '20-30': 411.6
                  },
                  goldPerMinDeltas: {
                      '10-20': 398.8,
                      '0-10': 218.1,
                      '20-30': 370
                  },
                  csDiffPerMinDeltas: {
                      '10-20': -2.1,
                      '0-10': -1.2999999999999998,
                      '20-30': -2.1
                  },
                  xpDiffPerMinDeltas: {
                      '10-20': 8.599999999999994,
                      '0-10': -28,
                      '20-30': -109.9
                  },
                  damageTakenPerMinDeltas: {
                      '10-20': 875.7,
                      '0-10': 433.1,
                      '20-30': 1785.3
                  },
                  damageTakenDiffPerMinDeltas: {
                      '10-20': 461.2,
                      '0-10': 243.70000000000005,
                      '20-30': 1040.1
                  },
                  role: 'SOLO',
                  lane: 'MIDDLE'
              }
          },
          {
              participantId: 9,
              teamId: 200,
              championId: 267,
              spell1Id: 4,
              spell2Id: 14,
              stats: {
                  participantId: 9,
                  win: true,
                  item0: 3853,
                  item1: 4005,
                  item2: 3117,
                  item3: 3504,
                  item4: 6616,
                  item5: 3916,
                  item6: 3364,
                  kills: 6,
                  deaths: 10,
                  assists: 17,
                  largestKillingSpree: 2,
                  largestMultiKill: 1,
                  killingSprees: 1,
                  longestTimeSpentLiving: 347,
                  doubleKills: 0,
                  tripleKills: 0,
                  quadraKills: 0,
                  pentaKills: 0,
                  unrealKills: 0,
                  totalDamageDealt: 42670,
                  magicDamageDealt: 25962,
                  physicalDamageDealt: 7777,
                  trueDamageDealt: 8930,
                  largestCriticalStrike: 77,
                  totalDamageDealtToChampions: 15076,
                  magicDamageDealtToChampions: 12244,
                  physicalDamageDealtToChampions: 1477,
                  trueDamageDealtToChampions: 1354,
                  totalHeal: 12677,
                  totalUnitsHealed: 5,
                  damageSelfMitigated: 8399,
                  damageDealtToObjectives: 3340,
                  damageDealtToTurrets: 1877,
                  visionScore: 55,
                  timeCCingOthers: 52,
                  totalDamageTaken: 20238,
                  magicalDamageTaken: 6714,
                  physicalDamageTaken: 13160,
                  trueDamageTaken: 364,
                  goldEarned: 10859,
                  goldSpent: 9700,
                  turretKills: 0,
                  inhibitorKills: 0,
                  totalMinionsKilled: 25,
                  neutralMinionsKilled: 0,
                  neutralMinionsKilledTeamJungle: 0,
                  neutralMinionsKilledEnemyJungle: 0,
                  totalTimeCrowdControlDealt: 170,
                  champLevel: 15,
                  visionWardsBoughtInGame: 5,
                  sightWardsBoughtInGame: 0,
                  wardsPlaced: 24,
                  wardsKilled: 9,
                  firstBloodKill: false,
                  firstBloodAssist: false,
                  firstTowerKill: false,
                  firstTowerAssist: false,
                  firstInhibitorKill: false,
                  firstInhibitorAssist: false,
                  combatPlayerScore: 0,
                  objectivePlayerScore: 0,
                  totalPlayerScore: 0,
                  totalScoreRank: 0,
                  playerScore0: 0,
                  playerScore1: 0,
                  playerScore2: 0,
                  playerScore3: 0,
                  playerScore4: 0,
                  playerScore5: 0,
                  playerScore6: 0,
                  playerScore7: 0,
                  playerScore8: 0,
                  playerScore9: 0,
                  perk0: 8229,
                  perk0Var1: 1558,
                  perk0Var2: 0,
                  perk0Var3: 0,
                  perk1: 8226,
                  perk1Var1: 250,
                  perk1Var2: 514,
                  perk1Var3: 0,
                  perk2: 8210,
                  perk2Var1: 21,
                  perk2Var2: 0,
                  perk2Var3: 0,
                  perk3: 8236,
                  perk3Var1: 48,
                  perk3Var2: 0,
                  perk3Var3: 0,
                  perk4: 8138,
                  perk4Var1: 30,
                  perk4Var2: 0,
                  perk4Var3: 0,
                  perk5: 8105,
                  perk5Var1: 13,
                  perk5Var2: 5,
                  perk5Var3: 0,
                  perkPrimaryStyle: 8200,
                  perkSubStyle: 8100,
                  statPerk0: 5008,
                  statPerk1: 5008,
                  statPerk2: 5001
              },
              timeline: {
                  participantId: 9,
                  creepsPerMinDeltas: {
                      '10-20': 1,
                      '0-10': 0.2,
                      '20-30': 0.6000000000000001
                  },
                  xpPerMinDeltas: {
                      '10-20': 325.9,
                      '0-10': 275.2,
                      '20-30': 510
                  },
                  goldPerMinDeltas: {
                      '10-20': 304.6,
                      '0-10': 207.5,
                      '20-30': 350.29999999999995
                  },
                  csDiffPerMinDeltas: {
                      '10-20': -0.04999999999999982,
                      '0-10': -0.6499999999999997,
                      '20-30': -0.24999999999999933
                  },
                  xpDiffPerMinDeltas: {
                      '10-20': -43.25000000000006,
                      '0-10': -12.09999999999998,
                      '20-30': 12.149999999999977
                  },
                  damageTakenPerMinDeltas: {
                      '10-20': 611.6,
                      '0-10': 328.7,
                      '20-30': 747.9
                  },
                  damageTakenDiffPerMinDeltas: {
                      '10-20': 39.19999999999999,
                      '0-10': -23.150000000000006,
                      '20-30': -225.8499999999999
                  },
                  role: 'DUO_SUPPORT',
                  lane: 'BOTTOM'
              }
          },
          {
              participantId: 10,
              teamId: 200,
              championId: 141,
              spell1Id: 14,
              spell2Id: 4,
              stats: {
                  participantId: 10,
                  win: true,
                  item0: 3074,
                  item1: 6630,
                  item2: 3065,
                  item3: 3047,
                  item4: 1029,
                  item5: 0,
                  item6: 3340,
                  kills: 4,
                  deaths: 8,
                  assists: 14,
                  largestKillingSpree: 2,
                  largestMultiKill: 1,
                  killingSprees: 2,
                  longestTimeSpentLiving: 515,
                  doubleKills: 0,
                  tripleKills: 0,
                  quadraKills: 0,
                  pentaKills: 0,
                  unrealKills: 0,
                  totalDamageDealt: 125960,
                  magicDamageDealt: 1201,
                  physicalDamageDealt: 122148,
                  trueDamageDealt: 2610,
                  largestCriticalStrike: 0,
                  totalDamageDealtToChampions: 24236,
                  magicDamageDealtToChampions: 417,
                  physicalDamageDealtToChampions: 21506,
                  trueDamageDealtToChampions: 2312,
                  totalHeal: 12372,
                  totalUnitsHealed: 1,
                  damageSelfMitigated: 30457,
                  damageDealtToObjectives: 10155,
                  damageDealtToTurrets: 3440,
                  visionScore: 12,
                  timeCCingOthers: 29,
                  totalDamageTaken: 37983,
                  magicalDamageTaken: 10945,
                  physicalDamageTaken: 24524,
                  trueDamageTaken: 2514,
                  goldEarned: 12446,
                  goldSpent: 11580,
                  turretKills: 1,
                  inhibitorKills: 0,
                  totalMinionsKilled: 160,
                  neutralMinionsKilled: 0,
                  neutralMinionsKilledTeamJungle: 0,
                  neutralMinionsKilledEnemyJungle: 0,
                  totalTimeCrowdControlDealt: 210,
                  champLevel: 16,
                  visionWardsBoughtInGame: 0,
                  sightWardsBoughtInGame: 0,
                  wardsPlaced: 8,
                  wardsKilled: 0,
                  firstBloodKill: false,
                  firstBloodAssist: false,
                  firstTowerKill: false,
                  firstTowerAssist: false,
                  firstInhibitorKill: false,
                  firstInhibitorAssist: false,
                  combatPlayerScore: 0,
                  objectivePlayerScore: 0,
                  totalPlayerScore: 0,
                  totalScoreRank: 0,
                  playerScore0: 0,
                  playerScore1: 0,
                  playerScore2: 0,
                  playerScore3: 0,
                  playerScore4: 0,
                  playerScore5: 0,
                  playerScore6: 0,
                  playerScore7: 0,
                  playerScore8: 0,
                  playerScore9: 0,
                  perk0: 8128,
                  perk0Var1: 814,
                  perk0Var2: 16,
                  perk0Var3: 0,
                  perk1: 8126,
                  perk1Var1: 736,
                  perk1Var2: 0,
                  perk1Var3: 0,
                  perk2: 8138,
                  perk2Var1: 18,
                  perk2Var2: 0,
                  perk2Var3: 0,
                  perk3: 8135,
                  perk3Var1: 1982,
                  perk3Var2: 5,
                  perk3Var3: 0,
                  perk4: 8453,
                  perk4Var1: 1965,
                  perk4Var2: 0,
                  perk4Var3: 0,
                  perk5: 8429,
                  perk5Var1: 64,
                  perk5Var2: 17,
                  perk5Var3: 14,
                  perkPrimaryStyle: 8100,
                  perkSubStyle: 8400,
                  statPerk0: 5007,
                  statPerk1: 5008,
                  statPerk2: 5002
              },
              timeline: {
                  participantId: 10,
                  creepsPerMinDeltas: {
                      '10-20': 7.800000000000001,
                      '0-10': 5.1,
                      '20-30': 2.1
                  },
                  xpPerMinDeltas: {
                      '10-20': 505.3,
                      '0-10': 365.7,
                      '20-30': 429.9
                  },
                  goldPerMinDeltas: {
                      '10-20': 441.70000000000005,
                      '0-10': 210.7,
                      '20-30': 349.2
                  },
                  csDiffPerMinDeltas: {
                      '10-20': 3.3,
                      '0-10': -2.3,
                      '20-30': -0.3999999999999998
                  },
                  xpDiffPerMinDeltas: {
                      '10-20': 166.60000000000002,
                      '0-10': -146.50000000000003,
                      '20-30': 22.600000000000023
                  },
                  damageTakenPerMinDeltas: {
                      '10-20': 886.8,
                      '0-10': 432.3,
                      '20-30': 1659.2
                  },
                  damageTakenDiffPerMinDeltas: {
                      '10-20': -28.80000000000001,
                      '0-10': 51.500000000000014,
                      '20-30': 190.89999999999998
                  },
                  role: 'SOLO',
                  lane: 'TOP'
              }
          }
      ],
      participantIdentities: [
          {
              participantId: 1,
              player: {
                  platformId: 'EUW1',
                  accountId: '2DAv_iurpcbb2caynkoYXRWnwoPfsrLlgTj9mEDbEv2YCw',
                  summonerName: 'Diable Exquis',
                  summonerId: '5aTMUN4Aw9Cbt6pAzk8jHFPNOBre_FyyU8QzYh36behfHjc',
                  currentPlatformId: 'EUW1',
                  currentAccountId: '2DAv_iurpcbb2caynkoYXRWnwoPfsrLlgTj9mEDbEv2YCw',
                  matchHistoryUri: '/v1/stats/player_history/EUW1/35352895',
                  profileIcon: 3017
              }
          },
          {
              participantId: 2,
              player: {
                  platformId: 'EUW1',
                  accountId: 'vtxmguIProKgHEfcfuB_30N1rmAIGQWv7qnVESNnm7WG4bfk5IYEaNux',
                  summonerName: 'Lulhum',
                  summonerId: 'sXIF4Mpl_GPGyVPqZockQg2-Rq4foh4D2OK6_aIDLw3FjMM8',
                  currentPlatformId: 'EUW1',
                  currentAccountId: 'vtxmguIProKgHEfcfuB_30N1rmAIGQWv7qnVESNnm7WG4bfk5IYEaNux',
                  matchHistoryUri: '/v1/stats/player_history/EUW1/2325560958906624',
                  profileIcon: 3543
              }
          },
          {
              participantId: 3,
              player: {
                  platformId: 'EUW1',
                  accountId: 'ZEgDXCYKfuWWz7QBxcs3u8izjLN31zHzQ-0Pfu2IBGhmaw',
                  summonerName: 'Bronathan',
                  summonerId: 'YjSFWbNFgT6Ull-b-D932yh4FZPYxd8W9rJGJVJBuQJqVI4',
                  currentPlatformId: 'EUW1',
                  currentAccountId: 'ZEgDXCYKfuWWz7QBxcs3u8izjLN31zHzQ-0Pfu2IBGhmaw',
                  matchHistoryUri: '/v1/stats/player_history/EUW1/40264985',
                  profileIcon: 7
              }
          },
          {
              participantId: 4,
              player: {
                  platformId: 'EUW1',
                  accountId: 'Ad6_N3xmO5agc1i0_KKresBe_V5EFkQv_IvbE523dOJ5QmI',
                  summonerName: 'Airomaks',
                  summonerId: 'Nz_rV67vy63QFvpbO02-G2cLUkNr5KEAYj6NB3pcCPP2upcb',
                  currentPlatformId: 'EUW1',
                  currentAccountId: 'Ad6_N3xmO5agc1i0_KKresBe_V5EFkQv_IvbE523dOJ5QmI',
                  matchHistoryUri: '/v1/stats/player_history/EUW1/234258056',
                  profileIcon: 3186
              }
          },
          {
              participantId: 5,
              player: {
                  platformId: 'EUW1',
                  accountId: 'YXhIcKlDBubK2P_y1kFJjTBHgQtcoojRDUzmdFrc54BpoA',
                  summonerName: 'JonnyBravo7',
                  summonerId: 'WQ_D3P-yeRYLiYNJSvyge6tY-786PfQasZVlVZSIRVsoLe4',
                  currentPlatformId: 'EUW1',
                  currentAccountId: 'YXhIcKlDBubK2P_y1kFJjTBHgQtcoojRDUzmdFrc54BpoA',
                  matchHistoryUri: '/v1/stats/player_history/EUW1/42423310',
                  profileIcon: 4644
              }
          },
          {
              participantId: 6,
              player: {
                  platformId: 'EUN1',
                  accountId: '9WwTtuOW85Zdjs-owhlZHAfvGRwalDPB2BD0elJsqjnNlw',
                  summonerName: 'sieberdreng',
                  summonerId: 'KLNFmcjHN6u8Pfx3qTCDKTZSmrQ3aVrIB3pM1irLhqV7hEg',
                  currentPlatformId: 'EUW1',
                  currentAccountId: '77xEvy3MpDCa13nRMjKuifmNegZgELfpCJJLKfTWXJRJlbo',
                  matchHistoryUri: '/v1/stats/player_history/EUN1/28816909',
                  profileIcon: 1301
              }
          },
          {
              participantId: 7,
              player: {
                  platformId: 'EUW1',
                  accountId: '_4Nsuh_19Hu1JbJEnhqEaK_x0-ooKuAbM81AmBgxO_5XWKA',
                  summonerName: 'Lyrae051',
                  summonerId: 'fA5VJDnRczUp5OHPzzBJJK2jklIcURDfWETI_96FOk0utnvy',
                  currentPlatformId: 'EUW1',
                  currentAccountId: '_4Nsuh_19Hu1JbJEnhqEaK_x0-ooKuAbM81AmBgxO_5XWKA',
                  matchHistoryUri: '/v1/stats/player_history/EUW1/234328987',
                  profileIcon: 4649
              }
          },
          {
              participantId: 8,
              player: {
                  platformId: 'EUW1',
                  accountId: 'RMT--oiKFgvMgOFZ_AAdPPBG6FPiEg_bYgiBe0_2CYTkCai403KsEoIO',
                  summonerName: 'talon1tricck',
                  summonerId: 'oDZtlrMW7y2aY7eEgyJY0XtosBKa89qFrLFK-cVJaL69Grt1Y4p_Hz-rBg',
                  currentPlatformId: 'EUW1',
                  currentAccountId: 'RMT--oiKFgvMgOFZ_AAdPPBG6FPiEg_bYgiBe0_2CYTkCai403KsEoIO',
                  matchHistoryUri: '/v1/stats/player_history/EUW1/2569868750841760',
                  profileIcon: 4783
              }
          },
          {
              participantId: 9,
              player: {
                  platformId: 'EUW1',
                  accountId: 'HOXzdLlB1y-WCm5o1Z2zXaq2q_8M6OclOzkHesd4vVXLis0igjjqRQW3',
                  summonerName: 'Lalloronaa',
                  summonerId: '9UBFxeEhP7VNO65HiGyVYDTnTU-MuD64lqXd9uql3_vPvhHO',
                  currentPlatformId: 'EUW1',
                  currentAccountId: 'HOXzdLlB1y-WCm5o1Z2zXaq2q_8M6OclOzkHesd4vVXLis0igjjqRQW3',
                  matchHistoryUri: '/v1/stats/player_history/EUW1/2433572421308960',
                  profileIcon: 3543
              }
          },
          {
              participantId: 10,
              player: {
                  platformId: 'EUW1',
                  accountId: 'N66Rb_6jmfzecUINsgyd27nD-249ONsJ2t7sEjtgGYs7fUyM0kkaOOGL',
                  summonerName: 'Cryper05',
                  summonerId: 'dKHla93EWZ7e55ItLWnma0IKO3-iBQk4qZH4A7Upbc2IH7mv',
                  currentPlatformId: 'EUW1',
                  currentAccountId: 'N66Rb_6jmfzecUINsgyd27nD-249ONsJ2t7sEjtgGYs7fUyM0kkaOOGL',
                  matchHistoryUri: '/v1/stats/player_history/EUW1/2157192277045760',
                  profileIcon: 4560
              }
          }
      ]
  };
    component.summonerSpell = [];
    component.runes = [];
    fixture.detectChanges();
  });

  it('should create', () => {
    expect(component).toBeTruthy();
  });
});
